### ISSUE TITLE
[CHORE] - Move images to CDN

### ISSUE THREAD

**Issue by naomi-lgbt** [RosaliaNightsong/RosaliaNightsong.github.io#455]
### What work needs to be performed?

We should remove the Becca images from this repository and use the hosted ones from our CDN.

## Art

- Remove the `src/assets/art` folder and all images within
- Update the gallery component in both instances ([1](https://github.com/RosaliaNightsong/RosaliaNightsong.github.io/blob/3438e959ddbab9d96fd4fe6b8a387e63878c8bd5/src/app/gallery/gallery.component.html#L5) and [2](        src="../../assets/art/{{ art.fileName }}")) to point to `https://cdn.naomi.lgbt/rosalia/art/{{ art.fileName }}`

## Games

- Remove the `src/assets/games` folder and all images within
- Update the games component in both instances ([1](https://github.com/RosaliaNightsong/RosaliaNightsong.github.io/blob/3438e959ddbab9d96fd4fe6b8a387e63878c8bd5/src/app/games/games.component.html#L5) and [2](https://github.com/RosaliaNightsong/RosaliaNightsong.github.io/blob/3438e959ddbab9d96fd4fe6b8a387e63878c8bd5/src/app/games/games.component.html#L8)) to point to `https://cdn.naomi.lgbt/rosalia/games/{{ game.fileName }}`

### Additional information

Work may begin at any time, but a PR that resolves this issue cannot be merged until the [relevant bot issue](https://github.com/RosaliaNightsong/discord-bot/issues/570) is resolved.

**Comment by abuna1985** [comment]
Now that the cdn link is in, can I please take on this issue?

**Comment by naomi-lgbt** [comment]
Sure!
